CREATE TABLE `locations` (
    `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `name` varchar(128) NOT NULL,
    `address` text,
    `modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);